import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Faq from "@/components/home/Faq";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Skill2rural app",
  description: "Generated by create next app",
};

export const clashDisplay = localFont({
  src: [
    {
      path: "../public/clash-display/ClashDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/clash-display/ClashDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public//clash-display/ClashDisplay-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/clash-display/ClashDisplay-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-clash",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" />
      <body className={`  ${clashDisplay.variable}`}>
        <NavBar />
        {children}
        <Faq />
        <Footer />
      </body>
    </html>
  );
}
